// Japanese Learning Data
// This file contains all the kana and kanji data for the NihonSupermemo app

// Katakana characters and their romaji readings
const katakana = {
    'ア': 'a', 'カ': 'ka', 'サ': 'sa', 'タ': 'ta', 'ナ': 'na', 'ハ': 'ha', 'マ': 'ma', 'ヤ': 'ya', 'ラ': 'ra', 'ワ': 'wa',
    'イ': 'i', 'キ': 'ki', 'シ': 'shi', 'チ': 'chi', 'ニ': 'ni', 'ヒ': 'hi', 'ミ': 'mi', 'リ': 'ri', 'ヰ': 'wi',
    'ウ': 'u', 'ク': 'ku', 'ス': 'su', 'ツ': 'tsu', 'ヌ': 'nu', 'フ': 'fu', 'ム': 'mu', 'ユ': 'yu', 'ル': 'ru',
    'エ': 'e', 'ケ': 'ke', 'セ': 'se', 'テ': 'te', 'ネ': 'ne', 'ヘ': 'he', 'メ': 'me', 'レ': 're', 'ヱ': 'we',
    'オ': 'o', 'コ': 'ko', 'ソ': 'so', 'ト': 'to', 'ノ': 'no', 'ホ': 'ho', 'モ': 'mo', 'ヨ': 'yo', 'ロ': 'ro', 'ヲ': 'wo', 'ン': 'n',
    
    // Dakuten (voiced)
    'ガ': 'ga', 'ザ': 'za', 'ダ': 'da', 'バ': 'ba',
    'ギ': 'gi', 'ジ': 'ji', 'ヂ': 'ji', 'ビ': 'bi',
    'グ': 'gu', 'ズ': 'zu', 'ヅ': 'zu', 'ブ': 'bu',
    'ゲ': 'ge', 'ゼ': 'ze', 'デ': 'de', 'ベ': 'be',
    'ゴ': 'go', 'ゾ': 'zo', 'ド': 'do', 'ボ': 'bo',
    
    // Handakuten (semi-voiced)
    'パ': 'pa', 'ピ': 'pi', 'プ': 'pu', 'ペ': 'pe', 'ポ': 'po',
    
    // Combinations with ya, yu, yo
    'キャ': 'kya', 'シャ': 'sha', 'チャ': 'cha', 'ニャ': 'nya', 'ヒャ': 'hya', 'ミャ': 'mya', 'リャ': 'rya', 'ギャ': 'gya', 'ジャ': 'ja', 'ビャ': 'bya', 'ピャ': 'pya',
    'キュ': 'kyu', 'シュ': 'shu', 'チュ': 'chu', 'ニュ': 'nyu', 'ヒュ': 'hyu', 'ミュ': 'myu', 'リュ': 'ryu', 'ギュ': 'gyu', 'ジュ': 'ju', 'ビュ': 'byu', 'ピュ': 'pyu',
    'キョ': 'kyo', 'ショ': 'sho', 'チョ': 'cho', 'ニョ': 'nyo', 'ヒョ': 'hyo', 'ミョ': 'myo', 'リョ': 'ryo', 'ギョ': 'gyo', 'ジョ': 'jo', 'ビョ': 'byo', 'ピョ': 'pyo'
};

// Hiragana characters and their romaji readings
const hiragana = {
    'あ': 'a', 'か': 'ka', 'さ': 'sa', 'た': 'ta', 'な': 'na', 'は': 'ha', 'ま': 'ma', 'や': 'ya', 'ら': 'ra', 'わ': 'wa',
    'い': 'i', 'き': 'ki', 'し': 'shi', 'ち': 'chi', 'に': 'ni', 'ひ': 'hi', 'み': 'mi', 'り': 'ri', 'ゐ': 'wi',
    'う': 'u', 'く': 'ku', 'す': 'su', 'つ': 'tsu', 'ぬ': 'nu', 'ふ': 'fu', 'む': 'mu', 'ゆ': 'yu', 'る': 'ru',
    'え': 'e', 'け': 'ke', 'せ': 'se', 'て': 'te', 'ね': 'ne', 'へ': 'he', 'め': 'me', 'れ': 're', 'ゑ': 'we',
    'お': 'o', 'こ': 'ko', 'そ': 'so', 'と': 'to', 'の': 'no', 'ほ': 'ho', 'も': 'mo', 'よ': 'yo', 'ろ': 'ro', 'を': 'wo', 'ん': 'n',
    
    // Dakuten (voiced)
    'が': 'ga', 'ざ': 'za', 'だ': 'da', 'ば': 'ba',
    'ぎ': 'gi', 'じ': 'ji', 'ぢ': 'ji', 'び': 'bi',
    'ぐ': 'gu', 'ず': 'zu', 'づ': 'zu', 'ぶ': 'bu',
    'げ': 'ge', 'ぜ': 'ze', 'で': 'de', 'べ': 'be',
    'ご': 'go', 'ぞ': 'zo', 'ど': 'do', 'ぼ': 'bo',
    
    // Handakuten (semi-voiced)
    'ぱ': 'pa', 'ぴ': 'pi', 'ぷ': 'pu', 'ぺ': 'pe', 'ぽ': 'po',
    
    // Combinations with ya, yu, yo
    'きゃ': 'kya', 'しゃ': 'sha', 'ちゃ': 'cha', 'にゃ': 'nya', 'ひゃ': 'hya', 'みゃ': 'mya', 'りゃ': 'rya', 'ぎゃ': 'gya', 'じゃ': 'ja', 'びゃ': 'bya', 'ぴゃ': 'pya',
    'きゅ': 'kyu', 'しゅ': 'shu', 'ちゅ': 'chu', 'にゅ': 'nyu', 'ひゅ': 'hyu', 'みゅ': 'myu', 'りゅ': 'ryu', 'ぎゅ': 'gyu', 'じゅ': 'ju', 'びゅ': 'byu', 'ぴゅ': 'pyu',
    'きょ': 'kyo', 'しょ': 'sho', 'ちょ': 'cho', 'にょ': 'nyo', 'ひょ': 'hyo', 'みょ': 'myo', 'りょ': 'ryo', 'ぎょ': 'gyo', 'じょ': 'jo', 'びょ': 'byo', 'ぴょ': 'pyo'
};

// Kanji characters with meanings and readings
// Structure: { character: { en: 'english meaning', fr: 'french meaning', romaji: ['reading1', 'reading2'] } }
const kanjiData = {
    // Numbers
    '一': { en: 'one', fr: 'un', romaji: ['ichi', 'itsu', 'hito'] },
    '二': { en: 'two', fr: 'deux', romaji: ['ni', 'futa'] },
    '三': { en: 'three', fr: 'trois', romaji: ['san', 'mitsu'] },
    '四': { en: 'four', fr: 'quatre', romaji: ['shi', 'yon', 'yo'] },
    '五': { en: 'five', fr: 'cinq', romaji: ['go', 'itsu'] },
    '六': { en: 'six', fr: 'six', romaji: ['roku', 'mu'] },
    '七': { en: 'seven', fr: 'sept', romaji: ['shichi', 'nana'] },
    '八': { en: 'eight', fr: 'huit', romaji: ['hachi', 'ya'] },
    '九': { en: 'nine', fr: 'neuf', romaji: ['kyuu', 'ku', 'kokono'] },
    '十': { en: 'ten', fr: 'dix', romaji: ['juu', 'to'] },
    '百': { en: 'hundred', fr: 'cent', romaji: ['hyaku', 'momo'] },
    '千': { en: 'thousand', fr: 'mille', romaji: ['sen', 'chi'] },
    '万': { en: 'ten thousand', fr: 'dix mille', romaji: ['man', 'ban'] },
    
    // Time and Calendar
    '日': { en: 'day/sun', fr: 'jour/soleil', romaji: ['nichi', 'jitsu', 'hi'] },
    '月': { en: 'month/moon', fr: 'mois/lune', romaji: ['getsu', 'gatsu', 'tsuki'] },
    '年': { en: 'year', fr: 'année', romaji: ['nen', 'toshi'] },
    '時': { en: 'time/hour', fr: 'temps/heure', romaji: ['ji', 'toki'] },
    '分': { en: 'minute/part', fr: 'minute/partie', romaji: ['fun', 'pun', 'bu', 'wa'] },
    '秒': { en: 'second', fr: 'seconde', romaji: ['byou'] },
    '今': { en: 'now', fr: 'maintenant', romaji: ['kon', 'kin', 'ima'] },
    '前': { en: 'before/front', fr: 'avant/devant', romaji: ['zen', 'mae'] },
    '後': { en: 'after/behind', fr: 'après/derrière', romaji: ['go', 'ato', 'ushi'] },
    '間': { en: 'interval/between', fr: 'intervalle/entre', romaji: ['kan', 'ken', 'aida', 'ma'] },
    '朝': { en: 'morning', fr: 'matin', romaji: ['chou', 'asa'] },
    '昼': { en: 'noon/daytime', fr: 'midi/jour', romaji: ['chuu', 'hiru'] },
    '夜': { en: 'night', fr: 'nuit', romaji: ['ya', 'yoru'] },
    '夕': { en: 'evening', fr: 'soir', romaji: ['yuu', 'yuube'] },
    
    // Days of the week
    '水': { en: 'water', fr: 'eau', romaji: ['sui', 'mizu'] },
    '火': { en: 'fire', fr: 'feu', romaji: ['ka', 'hi'] },
    '木': { en: 'tree/wood', fr: 'arbre/bois', romaji: ['moku', 'boku', 'ki'] },
    '金': { en: 'gold/money', fr: 'or/argent', romaji: ['kin', 'kon', 'kane'] },
    '土': { en: 'earth/soil', fr: 'terre/sol', romaji: ['do', 'to', 'tsuchi'] },
    
    // Family
    '父': { en: 'father', fr: 'père', romaji: ['fu', 'chichi'] },
    '母': { en: 'mother', fr: 'mère', romaji: ['bo', 'haha'] },
    '子': { en: 'child', fr: 'enfant', romaji: ['shi', 'su', 'ko'] },
    '男': { en: 'man/male', fr: 'homme/mâle', romaji: ['dan', 'nan', 'otoko'] },
    '女': { en: 'woman/female', fr: 'femme/femelle', romaji: ['jo', 'nyo', 'onna'] },
    '人': { en: 'person', fr: 'personne', romaji: ['jin', 'nin', 'hito'] },
    '友': { en: 'friend', fr: 'ami', romaji: ['yuu', 'tomo'] },
    '家': { en: 'house/family', fr: 'maison/famille', romaji: ['ka', 'ke', 'ie', 'ya'] },
    
    // Body parts
    '手': { en: 'hand', fr: 'main', romaji: ['shu', 'te'] },
    '足': { en: 'foot/leg', fr: 'pied/jambe', romaji: ['soku', 'ashi'] },
    '目': { en: 'eye', fr: 'œil', romaji: ['moku', 'boku', 'me'] },
    '口': { en: 'mouth', fr: 'bouche', romaji: ['kou', 'ku', 'kuchi'] },
    '耳': { en: 'ear', fr: 'oreille', romaji: ['ji', 'mimi'] },
    '頭': { en: 'head', fr: 'tête', romaji: ['tou', 'zu', 'atama', 'kashira'] },
    '心': { en: 'heart/mind', fr: 'cœur/esprit', romaji: ['shin', 'kokoro'] },
    '体': { en: 'body', fr: 'corps', romaji: ['tai', 'tei', 'karada'] },
    '声': { en: 'voice', fr: 'voix', romaji: ['sei', 'koe'] },
    
    // Nature and elements
    '山': { en: 'mountain', fr: 'montagne', romaji: ['san', 'zan', 'yama'] },
    '川': { en: 'river', fr: 'rivière', romaji: ['sen', 'kawa', 'gawa'] },
    '海': { en: 'sea/ocean', fr: 'mer/océan', romaji: ['kai', 'umi'] },
    '空': { en: 'sky/empty', fr: 'ciel/vide', romaji: ['kuu', 'sora', 'kara'] },
    '雨': { en: 'rain', fr: 'pluie', romaji: ['u', 'ame'] },
    '雪': { en: 'snow', fr: 'neige', romaji: ['setsu', 'yuki'] },
    '風': { en: 'wind', fr: 'vent', romaji: ['fuu', 'kaze'] },
    '花': { en: 'flower', fr: 'fleur', romaji: ['ka', 'hana'] },
    '草': { en: 'grass', fr: 'herbe', romaji: ['sou', 'kusa'] },
    '森': { en: 'forest', fr: 'forêt', romaji: ['shin', 'mori'] },
    '石': { en: 'stone', fr: 'pierre', romaji: ['seki', 'shaku', 'ishi'] },
    
    // Animals
    '犬': { en: 'dog', fr: 'chien', romaji: ['ken', 'inu'] },
    '猫': { en: 'cat', fr: 'chat', romaji: ['byou', 'neko'] },
    '魚': { en: 'fish', fr: 'poisson', romaji: ['gyo', 'sakana', 'uo'] },
    '鳥': { en: 'bird', fr: 'oiseau', romaji: ['chou', 'tori'] },
    '虫': { en: 'insect', fr: 'insecte', romaji: ['chuu', 'mushi'] },
    
    // Colors
    '白': { en: 'white', fr: 'blanc', romaji: ['haku', 'byaku', 'shiro', 'shira'] },
    '黒': { en: 'black', fr: 'noir', romaji: ['koku', 'kuro'] },
    '赤': { en: 'red', fr: 'rouge', romaji: ['seki', 'shaku', 'aka'] },
    '青': { en: 'blue', fr: 'bleu', romaji: ['sei', 'shou', 'ao'] },
    '黄': { en: 'yellow', fr: 'jaune', romaji: ['ou', 'ko', 'ki'] },
    '茶': { en: 'tea/brown', fr: 'thé/brun', romaji: ['cha', 'sa'] },
    
    // Food and drink
    '食': { en: 'eat/food', fr: 'manger/nourriture', romaji: ['shoku', 'jiki', 'ta', 'ku'] },
    '飲': { en: 'drink', fr: 'boire', romaji: ['in', 'no'] },
    '水': { en: 'water', fr: 'eau', romaji: ['sui', 'mizu'] },
    '茶': { en: 'tea', fr: 'thé', romaji: ['cha', 'sa'] },
    '米': { en: 'rice', fr: 'riz', romaji: ['bei', 'mai', 'kome'] },
    '肉': { en: 'meat', fr: 'viande', romaji: ['niku'] },
    '牛': { en: 'cow', fr: 'vache', romaji: ['gyuu', 'ushi'] },
    '豚': { en: 'pig', fr: 'porc', romaji: ['ton', 'buta'] },
    '鶏': { en: 'chicken', fr: 'poulet', romaji: ['kei', 'niwatori'] },
    
    // Directions and positions
    '東': { en: 'east', fr: 'est', romaji: ['tou', 'higashi'] },
    '西': { en: 'west', fr: 'ouest', romaji: ['sei', 'sai', 'nishi'] },
    '南': { en: 'south', fr: 'sud', romaji: ['nan', 'minami'] },
    '北': { en: 'north', fr: 'nord', romaji: ['hoku', 'kita'] },
    '右': { en: 'right', fr: 'droite', romaji: ['u', 'yuu', 'migi'] },
    '左': { en: 'left', fr: 'gauche', romaji: ['sa', 'hidari'] },
    '上': { en: 'up/above', fr: 'haut/au-dessus', romaji: ['jou', 'shou', 'ue', 'kami', 'a', 'nobo'] },
    '下': { en: 'down/below', fr: 'bas/en-dessous', romaji: ['ka', 'ge', 'shita', 'shimo', 'moto', 'sa', 'kuda', 'o'] },
    '中': { en: 'middle/inside', fr: 'milieu/à l\'intérieur', romaji: ['chuu', 'juu', 'naka', 'uchi'] },
    '外': { en: 'outside', fr: 'dehors', romaji: ['gai', 'ge', 'soto', 'hoka'] },
    '内': { en: 'inside', fr: 'à l\'intérieur', romaji: ['nai', 'dai', 'uchi'] },
    '近': { en: 'near', fr: 'proche', romaji: ['kin', 'chika'] },
    '遠': { en: 'far', fr: 'loin', romaji: ['en', 'on', 'too'] },
    
    // Actions and verbs
    '行': { en: 'go', fr: 'aller', romaji: ['kou', 'gyou', 'i', 'yu', 'okona'] },
    '来': { en: 'come', fr: 'venir', romaji: ['rai', 'ku', 'ko'] },
    '帰': { en: 'return', fr: 'retourner', romaji: ['ki', 'kae'] },
    '出': { en: 'exit/go out', fr: 'sortir', romaji: ['shutsu', 'sui', 'de', 'da'] },
    '入': { en: 'enter', fr: 'entrer', romaji: ['nyuu', 'ju', 'i', 'hai'] },
    '立': { en: 'stand', fr: 'se tenir debout', romaji: ['ritsu', 'ryuu', 'ta'] },
    '座': { en: 'sit', fr: 's\'asseoir', romaji: ['za', 'suwa'] },
    '歩': { en: 'walk', fr: 'marcher', romaji: ['ho', 'bu', 'aru', 'ayu'] },
    '走': { en: 'run', fr: 'courir', romaji: ['sou', 'hashi'] },
    '止': { en: 'stop', fr: 'arrêter', romaji: ['shi', 'to', 'ya'] },
    '休': { en: 'rest', fr: 'se reposer', romaji: ['kyuu', 'yasu'] },
    '働': { en: 'work', fr: 'travailler', romaji: ['dou', 'hatara'] },
    '住': { en: 'live/reside', fr: 'habiter', romaji: ['juu', 'su'] },
    '死': { en: 'die', fr: 'mourir', romaji: ['shi', 'shi'] },
    '生': { en: 'live/birth', fr: 'vivre/naissance', romaji: ['sei', 'shou', 'i', 'u', 'o', 'ha', 'ki', 'nama'] },
    '見': { en: 'see', fr: 'voir', romaji: ['ken', 'mi'] },
    '聞': { en: 'hear/ask', fr: 'entendre/demander', romaji: ['bun', 'mon', 'ki'] },
    '読': { en: 'read', fr: 'lire', romaji: ['doku', 'toku', 'yo'] },
    '書': { en: 'write', fr: 'écrire', romaji: ['sho', 'ka'] },
    '話': { en: 'speak/story', fr: 'parler/histoire', romaji: ['wa', 'hanashi', 'hana'] },
    '言': { en: 'say', fr: 'dire', romaji: ['gen', 'gon', 'i', 'koto'] },
    '思': { en: 'think', fr: 'penser', romaji: ['shi', 'omo'] },
    '知': { en: 'know', fr: 'savoir', romaji: ['chi', 'shi'] },
    '作': { en: 'make', fr: 'faire', romaji: ['saku', 'sa', 'tsuku'] },
    '使': { en: 'use', fr: 'utiliser', romaji: ['shi', 'tsuka'] },
    '持': { en: 'hold', fr: 'tenir', romaji: ['ji', 'mo'] },
    '取': { en: 'take', fr: 'prendre', romaji: ['shu', 'to'] },
    '買': { en: 'buy', fr: 'acheter', romaji: ['bai', 'ka'] },
    '売': { en: 'sell', fr: 'vendre', romaji: ['bai', 'u'] },
    '開': { en: 'open', fr: 'ouvrir', romaji: ['kai', 'a', 'hira'] },
    '閉': { en: 'close', fr: 'fermer', romaji: ['hei', 'shi', 'to'] },
    '始': { en: 'begin', fr: 'commencer', romaji: ['shi', 'haji'] },
    '終': { en: 'end', fr: 'finir', romaji: ['shuu', 'o'] },
    '切': { en: 'cut', fr: 'couper', romaji: ['setsu', 'sai', 'ki'] },
    '洗': { en: 'wash', fr: 'laver', romaji: ['sen', 'ara'] },
    '着': { en: 'wear/arrive', fr: 'porter/arriver', romaji: ['chaku', 'jaku', 'ki', 'tsu'] },
    '脱': { en: 'take off', fr: 'enlever', romaji: ['datsu', 'nu'] },
    
    // School and learning
    '学': { en: 'study/learning', fr: 'étude/apprentissage', romaji: ['gaku', 'mana'] },
    '校': { en: 'school', fr: 'école', romaji: ['kou'] },
    '先': { en: 'previous/ahead', fr: 'précédent/devant', romaji: ['sen', 'saki', 'ma'] },
    '生': { en: 'student/life', fr: 'étudiant/vie', romaji: ['sei', 'shou', 'nama', 'i', 'u', 'o'] },
    '教': { en: 'teach', fr: 'enseigner', romaji: ['kyou', 'oshi'] },
    '習': { en: 'learn', fr: 'apprendre', romaji: ['shuu', 'nara'] },
    '勉': { en: 'diligence', fr: 'diligence', romaji: ['ben', 'tsuto'] },
    '強': { en: 'strong/study', fr: 'fort/étudier', romaji: ['kyou', 'gou', 'tsuyo', 'shi'] },
    '試': { en: 'test/try', fr: 'test/essayer', romaji: ['shi', 'kokoro', 'tame'] },
    '験': { en: 'examine', fr: 'examiner', romaji: ['ken', 'gen'] },
    '問': { en: 'question', fr: 'question', romaji: ['mon', 'to'] },
    '答': { en: 'answer', fr: 'réponse', romaji: ['tou', 'kota'] },
    
    // Places
    '国': { en: 'country', fr: 'pays', romaji: ['koku', 'kuni'] },
    '町': { en: 'town', fr: 'ville', romaji: ['chou', 'machi'] },
    '市': { en: 'city', fr: 'ville', romaji: ['shi', 'ichi'] },
    '村': { en: 'village', fr: 'village', romaji: ['son', 'mura'] },
    '道': { en: 'road/way', fr: 'route/chemin', romaji: ['dou', 'tou', 'michi'] },
    '駅': { en: 'station', fr: 'gare', romaji: ['eki'] },
    '店': { en: 'shop', fr: 'magasin', romaji: ['ten', 'mise'] },
    '建': { en: 'build', fr: 'construire', romaji: ['ken', 'kon', 'ta'] },
    '物': { en: 'thing/building', fr: 'chose/bâtiment', romaji: ['butsu', 'motsu', 'mono'] },
    '所': { en: 'place', fr: 'lieu', romaji: ['sho', 'tokoro'] },
    '場': { en: 'place/field', fr: 'lieu/champ', romaji: ['jou', 'ba'] },
    '病': { en: 'sick/illness', fr: 'malade/maladie', romaji: ['byou', 'hei', 'ya'] },
    '院': { en: 'institution', fr: 'institution', romaji: ['in'] },
    '銀': { en: 'silver', fr: 'argent', romaji: ['gin'] },
    
    // Transportation
    '車': { en: 'car/vehicle', fr: 'voiture/véhicule', romaji: ['sha', 'kuruma'] },
    '電': { en: 'electricity', fr: 'électricité', romaji: ['den'] },
    '汽': { en: 'steam', fr: 'vapeur', romaji: ['ki'] },
    '船': { en: 'ship', fr: 'bateau', romaji: ['sen', 'fune', 'funa'] },
    '飛': { en: 'fly', fr: 'voler', romaji: ['hi', 'to'] },
    '機': { en: 'machine', fr: 'machine', romaji: ['ki', 'hata'] },
    
    // Weather and seasons
    '春': { en: 'spring', fr: 'printemps', romaji: ['shun', 'haru'] },
    '夏': { en: 'summer', fr: 'été', romaji: ['ka', 'ge', 'natsu'] },
    '秋': { en: 'autumn', fr: 'automne', romaji: ['shuu', 'aki'] },
    '冬': { en: 'winter', fr: 'hiver', romaji: ['tou', 'fuyu'] },
    '暑': { en: 'hot', fr: 'chaud', romaji: ['sho', 'atsu'] },
    '寒': { en: 'cold', fr: 'froid', romaji: ['kan', 'samu'] },
    '暖': { en: 'warm', fr: 'chaud', romaji: ['dan', 'atata'] },
    '涼': { en: 'cool', fr: 'frais', romaji: ['ryou', 'suzu'] },
    
    // Adjectives and descriptions
    '大': { en: 'big', fr: 'grand', romaji: ['dai', 'tai', 'oo'] },
    '小': { en: 'small', fr: 'petit', romaji: ['shou', 'ko', 'chii'] },
    '高': { en: 'high/expensive', fr: 'haut/cher', romaji: ['kou', 'taka'] },
    '低': { en: 'low', fr: 'bas', romaji: ['tei', 'hiku'] },
    '長': { en: 'long', fr: 'long', romaji: ['chou', 'naga'] },
    '短': { en: 'short', fr: 'court', romaji: ['tan', 'mijika'] },
    '太': { en: 'fat/thick', fr: 'gros/épais', romaji: ['tai', 'ta', 'futo'] },
    '細': { en: 'thin/narrow', fr: 'mince/étroit', romaji: ['sai', 'hoso'] },
    '広': { en: 'wide', fr: 'large', romaji: ['kou', 'hiro'] },
    '狭': { en: 'narrow', fr: 'étroit', romaji: ['kyou', 'sema'] },
    '重': { en: 'heavy', fr: 'lourd', romaji: ['juu', 'chou', 'omo', 'kasa'] },
    '軽': { en: 'light', fr: 'léger', romaji: ['kei', 'karu'] },
    '新': { en: 'new', fr: 'nouveau', romaji: ['shin', 'atara', 'ara', 'nii'] },
    '古': { en: 'old', fr: 'vieux', romaji: ['ko', 'furu'] },
    '若': { en: 'young', fr: 'jeune', romaji: ['jaku', 'nyaku', 'waka'] },
    '早': { en: 'early/fast', fr: 'tôt/rapide', romaji: ['sou', 'sa', 'haya'] },
    '遅': { en: 'late/slow', fr: 'tard/lent', romaji: ['chi', 'oso'] },
    '速': { en: 'fast', fr: 'rapide', romaji: ['soku', 'haya'] },
    '多': { en: 'many', fr: 'beaucoup', romaji: ['ta', 'oo'] },
    '少': { en: 'few/little', fr: 'peu', romaji: ['shou', 'suko', 'suku'] },
    '元': { en: 'origin', fr: 'origine', romaji: ['gen', 'gan', 'moto'] },
    '気': { en: 'spirit/energy', fr: 'esprit/énergie', romaji: ['ki', 'ke'] },
    '安': { en: 'safe/cheap', fr: 'sûr/pas cher', romaji: ['an', 'yasu'] },
    '危': { en: 'dangerous', fr: 'dangereux', romaji: ['ki', 'aya'] },
    '正': { en: 'correct', fr: 'correct', romaji: ['sei', 'shou', 'tada'] },
    '悪': { en: 'bad', fr: 'mauvais', romaji: ['aku', 'o', 'waru'] },
    '良': { en: 'good', fr: 'bon', romaji: ['ryou', 'yo', 'i'] },
    '美': { en: 'beauty', fr: 'beauté', romaji: ['bi', 'utsuku'] },
    '親': { en: 'parent/intimate', fr: 'parent/intime', romaji: ['shin', 'oya', 'shita'] },
    '便': { en: 'convenience', fr: 'commodité', romaji: ['ben', 'bin', 'tayo'] },
    '利': { en: 'profit/benefit', fr: 'profit/bénéfice', romaji: ['ri', 'ki'] },
    
    // Emotions and feelings
    '楽': { en: 'enjoyment/easy', fr: 'plaisir/facile', romaji: ['raku', 'gaku', 'tano'] },
    '苦': { en: 'suffering', fr: 'souffrance', romaji: ['ku', 'niga', 'kuru'] },
    '痛': { en: 'pain', fr: 'douleur', romaji: ['tsuu', 'ita'] },
    '辛': { en: 'spicy/painful', fr: 'épicé/pénible', romaji: ['shin', 'kara', 'tsura'] },
    '怒': { en: 'anger', fr: 'colère', romaji: ['do', 'nu', 'ika', 'oko'] },
    '悲': { en: 'sadness', fr: 'tristesse', romaji: ['hi', 'kana'] },
    '喜': { en: 'joy', fr: 'joie', romaji: ['ki', 'yoroko'] },
    '愛': { en: 'love', fr: 'amour', romaji: ['ai'] },
    '恋': { en: 'romantic love', fr: 'amour romantique', romaji: ['ren', 'koi'] },
    
    // Abstract concepts
    '事': { en: 'matter/thing', fr: 'affaire/chose', romaji: ['ji', 'zu', 'koto'] },
    '何': { en: 'what', fr: 'quoi', romaji: ['ka', 'nani', 'nan'] },
    '物': { en: 'thing', fr: 'chose', romaji: ['butsu', 'motsu', 'mono'] },
    '者': { en: 'person', fr: 'personne', romaji: ['sha', 'mono'] },
    '方': { en: 'direction/way', fr: 'direction/façon', romaji: ['hou', 'kata', 'gata'] },
    '自': { en: 'self', fr: 'soi', romaji: ['ji', 'shi', 'mizuka'] },
    '他': { en: 'other', fr: 'autre', romaji: ['ta', 'hoka'] },
    '同': { en: 'same', fr: 'même', romaji: ['dou', 'ona'] },
    '全': { en: 'all/whole', fr: 'tout/entier', romaji: ['zen', 'matta'] },
    '部': { en: 'part', fr: 'partie', romaji: ['bu'] },
    '半': { en: 'half', fr: 'moitié', romaji: ['han', 'naka'] },
    '別': { en: 'separate', fr: 'séparé', romaji: ['betsu', 'waka'] },
    '特': { en: 'special', fr: 'spécial', romaji: ['toku'] },
    '必': { en: 'necessary', fr: 'nécessaire', romaji: ['hitsu', 'kanara'] },
    '要': { en: 'necessary/want', fr: 'nécessaire/vouloir', romaji: ['you', 'i', 'kana'] },
    '不': { en: 'not', fr: 'ne pas', romaji: ['fu', 'bu'] },
    '無': { en: 'nothing', fr: 'rien', romaji: ['mu', 'bu', 'na'] },
    '有': { en: 'exist/have', fr: 'exister/avoir', romaji: ['yuu', 'u', 'a'] },
    '共': { en: 'together', fr: 'ensemble', romaji: ['kyou', 'tomo'] },
    
    // Work and business
    '会': { en: 'meet/society', fr: 'rencontrer/société', romaji: ['kai', 'e', 'a'] },
    '社': { en: 'company', fr: 'entreprise', romaji: ['sha', 'yashiro'] },
    '員': { en: 'member', fr: 'membre', romaji: ['in'] },
    '客': { en: 'customer', fr: 'client', romaji: ['kyaku', 'kaku'] },
    '仕': { en: 'serve', fr: 'servir', romaji: ['shi', 'tsuka'] },
    '事': { en: 'work/matter', fr: 'travail/affaire', romaji: ['ji', 'zu', 'koto'] },
    '業': { en: 'business', fr: 'affaires', romaji: ['gyou', 'waza'] },
    '職': { en: 'job', fr: 'travail', romaji: ['shoku'] },
    '務': { en: 'duty', fr: 'devoir', romaji: ['mu', 'tsuto'] },
    
    // Technology and modern life
    '機': { en: 'machine', fr: 'machine', romaji: ['ki', 'hata'] },
    '器': { en: 'tool/vessel', fr: 'outil/récipient', romaji: ['ki', 'utsuwa'] },
    '具': { en: 'tool', fr: 'outil', romaji: ['gu', 'sona'] },
    '材': { en: 'material', fr: 'matériau', romaji: ['zai'] },
    '料': { en: 'material/fee', fr: 'matériau/frais', romaji: ['ryou'] },
    '品': { en: 'goods', fr: 'marchandises', romaji: ['hin', 'shina'] },
    
    // Money and economics
    '金': { en: 'money/gold', fr: 'argent/or', romaji: ['kin', 'kon', 'kane'] },
    '円': { en: 'yen/circle', fr: 'yen/cercle', romaji: ['en', 'maru'] },
    '値': { en: 'price/value', fr: 'prix/valeur', romaji: ['chi', 'ne', 'atai'] },
    '段': { en: 'step/level', fr: 'étape/niveau', romaji: ['dan'] },
    '代': { en: 'price/generation', fr: 'prix/génération', romaji: ['dai', 'tai', 'ka', 'yo', 'shiro'] },
    
    // Miscellaneous common kanji
    '回': { en: 'times/rotate', fr: 'fois/tourner', romaji: ['kai', 'e', 'mawa'] },
    '度': { en: 'degree/times', fr: 'degré/fois', romaji: ['do', 'to', 'tabi'] },
    '番': { en: 'number/turn', fr: 'numéro/tour', romaji: ['ban'] },
    '平': { en: 'flat/peace', fr: 'plat/paix', romaji: ['hei', 'byou', 'hira', 'tai'] },
    '注': { en: 'pour/attention', fr: 'verser/attention', romaji: ['chuu', 'so'] },
    '意': { en: 'mind/meaning', fr: 'esprit/sens', romaji: ['i'] },
    '味': { en: 'taste/flavor', fr: 'goût/saveur', romaji: ['mi', 'aji'] },
    '質': { en: 'quality', fr: 'qualité', romaji: ['shitsu', 'shichi', 'chi'] },
    '文': { en: 'sentence/culture', fr: 'phrase/culture', romaji: ['bun', 'mon', 'fumi'] },
    '字': { en: 'character/letter', fr: 'caractère/lettre', romaji: ['ji', 'aza'] },
    '言': { en: 'word/say', fr: 'mot/dire', romaji: ['gen', 'gon', 'i', 'koto'] },
    '語': { en: 'language', fr: 'langue', romaji: ['go', 'kata'] },
    '計': { en: 'measure/plan', fr: 'mesurer/plan', romaji: ['kei', 'haka'] },
    '算': { en: 'calculate', fr: 'calculer', romaji: ['san'] },
    '数': { en: 'number', fr: 'nombre', romaji: ['suu', 'su', 'kazu', 'kazo'] },
    '理': { en: 'reason', fr: 'raison', romaji: ['ri'] },
    '科': { en: 'subject/department', fr: 'matière/département', romaji: ['ka'] },
    '歴': { en: 'history', fr: 'histoire', romaji: ['reki'] },
    '史': { en: 'history', fr: 'histoire', romaji: ['shi'] },
    '化': { en: 'change', fr: 'changement', romaji: ['ka', 'ke', 'ba'] },
    '変': { en: 'change', fr: 'changement', romaji: ['hen', 'ka'] },
    '点': { en: 'point', fr: 'point', romaji: ['ten'] },
    '線': { en: 'line', fr: 'ligne', romaji: ['sen'] },
    '形': { en: 'shape', fr: 'forme', romaji: ['kei', 'gyou', 'kata'] },
    '色': { en: 'color', fr: 'couleur', romaji: ['shoku', 'shiki', 'iro'] },
    '光': { en: 'light', fr: 'lumière', romaji: ['kou', 'hikari'] },
    '音': { en: 'sound', fr: 'son', romaji: ['on', 'in', 'oto', 'ne'] },
    '歌': { en: 'song', fr: 'chanson', romaji: ['ka', 'uta'] },
    '絵': { en: 'picture', fr: 'image', romaji: ['kai', 'e'] },
    '写': { en: 'copy/photograph', fr: 'copier/photographier', romaji: ['sha', 'utsu'] },
    '真': { en: 'true/real', fr: 'vrai/réel', romaji: ['shin', 'ma'] },
    '映': { en: 'reflect/project', fr: 'refléter/projeter', romaji: ['ei', 'utsu', 'ha'] },
    '画': { en: 'picture/stroke', fr: 'image/trait', romaji: ['ga', 'kaku'] },
    '館': { en: 'building/hall', fr: 'bâtiment/salle', romaji: ['kan', 'yakata'] },
    '図': { en: 'diagram', fr: 'diagramme', romaji: ['zu', 'to', 'haka'] },
    '紙': { en: 'paper', fr: 'papier', romaji: ['shi', 'kami'] },
    '服': { en: 'clothes', fr: 'vêtements', romaji: ['fuku'] },
    '毛': { en: 'hair/fur', fr: 'cheveu/fourrure', romaji: ['mou', 'ke'] },
    '皮': { en: 'skin/leather', fr: 'peau/cuir', romaji: ['hi', 'kawa'] },
    '週': { en: 'week', fr: 'semaine', romaji: ['shuu'] },
    '曜': { en: 'day of the week', fr: 'jour de la semaine', romaji: ['you'] },
    '昨': { en: 'yesterday', fr: 'hier', romaji: ['saku'] },
    '毎': { en: 'every', fr: 'chaque', romaji: ['mai'] },
    '去': { en: 'go away/past', fr: 'partir/passé', romaji: ['kyo', 'ko', 'sa'] },
    '次': { en: 'next', fr: 'suivant', romaji: ['ji', 'shi', 'tsugi'] },
    '最': { en: 'most', fr: 'plus', romaji: ['sai', 'motto'] },
    '初': { en: 'first/beginning', fr: 'premier/début', romaji: ['sho', 'hatsu', 'haji', 'ui', 'som'] },
    '終': { en: 'end', fr: 'fin', romaji: ['shuu', 'o'] },
    '決': { en: 'decide', fr: 'décider', romaji: ['ketsu', 'ki'] },
    '定': { en: 'determine/fixed', fr: 'déterminer/fixe', romaji: ['tei', 'jo', 'sada'] },
    '約': { en: 'promise/approximately', fr: 'promesse/environ', romaji: ['yaku'] },
    '束': { en: 'bundle', fr: 'faisceau', romaji: ['soku', 'taba'] },
    '続': { en: 'continue', fr: 'continuer', romaji: ['zoku', 'shoku', 'tsuzu'] },
    '信': { en: 'believe/trust', fr: 'croire/confiance', romaji: ['shin'] },
    '頼': { en: 'rely on/request', fr: 'compter sur/demander', romaji: ['rai', 'tano', 'tayo'] },
    '相': { en: 'mutual', fr: 'mutuel', romaji: ['sou', 'sho', 'ai'] },
    '談': { en: 'discuss', fr: 'discuter', romaji: ['dan'] },
    '結': { en: 'tie/result', fr: 'lier/résultat', romaji: ['ketsu', 'musu', 'yu'] },
    '婚': { en: 'marriage', fr: 'mariage', romaji: ['kon'] },
    '礼': { en: 'courtesy', fr: 'courtoisie', romaji: ['rei', 'ra'] },
    '祝': { en: 'celebrate', fr: 'célébrer', romaji: ['shuku', 'iwa'] },
    '祭': { en: 'festival', fr: 'festival', romaji: ['sai', 'matsuri'] },
    '宿': { en: 'inn/lodging', fr: 'auberge/logement', romaji: ['shuku', 'yado'] },
    '泊': { en: 'stay overnight', fr: 'passer la nuit', romaji: ['haku', 'to'] },
    '旅': { en: 'travel', fr: 'voyage', romaji: ['ryo', 'tabi'] },
    '温': { en: 'warm', fr: 'chaud', romaji: ['on', 'atata'] },
    '冷': { e: 'cold', fr: 'froid', romaji: ['rei', 'tsume', 'hi', 'sa'] }
};