# -*- coding: utf-8 -*-
"""Generate colors.js for ChromaCam from the verified CSS3 palette plus a
curated set of traditional / pigment colours that matter in French."""
import json, io, sys

# The 147 CSS3/X11 named colours and their authoritative hex values
# (cross-checked against the `webcolors` package's CSS3 table).
CSS_HEX = {
    'aliceblue':             '#F0F8FF',
    'antiquewhite':          '#FAEBD7',
    'aqua':                  '#00FFFF',
    'aquamarine':            '#7FFFD4',
    'azure':                 '#F0FFFF',
    'beige':                 '#F5F5DC',
    'bisque':                '#FFE4C4',
    'black':                 '#000000',
    'blanchedalmond':        '#FFEBCD',
    'blue':                  '#0000FF',
    'blueviolet':            '#8A2BE2',
    'brown':                 '#A52A2A',
    'burlywood':             '#DEB887',
    'cadetblue':             '#5F9EA0',
    'chartreuse':            '#7FFF00',
    'chocolate':             '#D2691E',
    'coral':                 '#FF7F50',
    'cornflowerblue':        '#6495ED',
    'cornsilk':              '#FFF8DC',
    'crimson':               '#DC143C',
    'cyan':                  '#00FFFF',
    'darkblue':              '#00008B',
    'darkcyan':              '#008B8B',
    'darkgoldenrod':         '#B8860B',
    'darkgray':              '#A9A9A9',
    'darkgreen':             '#006400',
    'darkgrey':              '#A9A9A9',
    'darkkhaki':             '#BDB76B',
    'darkmagenta':           '#8B008B',
    'darkolivegreen':        '#556B2F',
    'darkorange':            '#FF8C00',
    'darkorchid':            '#9932CC',
    'darkred':               '#8B0000',
    'darksalmon':            '#E9967A',
    'darkseagreen':          '#8FBC8F',
    'darkslateblue':         '#483D8B',
    'darkslategray':         '#2F4F4F',
    'darkslategrey':         '#2F4F4F',
    'darkturquoise':         '#00CED1',
    'darkviolet':            '#9400D3',
    'deeppink':              '#FF1493',
    'deepskyblue':           '#00BFFF',
    'dimgray':               '#696969',
    'dimgrey':               '#696969',
    'dodgerblue':            '#1E90FF',
    'firebrick':             '#B22222',
    'floralwhite':           '#FFFAF0',
    'forestgreen':           '#228B22',
    'fuchsia':               '#FF00FF',
    'gainsboro':             '#DCDCDC',
    'ghostwhite':            '#F8F8FF',
    'gold':                  '#FFD700',
    'goldenrod':             '#DAA520',
    'gray':                  '#808080',
    'green':                 '#008000',
    'greenyellow':           '#ADFF2F',
    'grey':                  '#808080',
    'honeydew':              '#F0FFF0',
    'hotpink':               '#FF69B4',
    'indianred':             '#CD5C5C',
    'indigo':                '#4B0082',
    'ivory':                 '#FFFFF0',
    'khaki':                 '#F0E68C',
    'lavender':              '#E6E6FA',
    'lavenderblush':         '#FFF0F5',
    'lawngreen':             '#7CFC00',
    'lemonchiffon':          '#FFFACD',
    'lightblue':             '#ADD8E6',
    'lightcoral':            '#F08080',
    'lightcyan':             '#E0FFFF',
    'lightgoldenrodyellow':  '#FAFAD2',
    'lightgray':             '#D3D3D3',
    'lightgreen':            '#90EE90',
    'lightgrey':             '#D3D3D3',
    'lightpink':             '#FFB6C1',
    'lightsalmon':           '#FFA07A',
    'lightseagreen':         '#20B2AA',
    'lightskyblue':          '#87CEFA',
    'lightslategray':        '#778899',
    'lightslategrey':        '#778899',
    'lightsteelblue':        '#B0C4DE',
    'lightyellow':           '#FFFFE0',
    'lime':                  '#00FF00',
    'limegreen':             '#32CD32',
    'linen':                 '#FAF0E6',
    'magenta':               '#FF00FF',
    'maroon':                '#800000',
    'mediumaquamarine':      '#66CDAA',
    'mediumblue':            '#0000CD',
    'mediumorchid':          '#BA55D3',
    'mediumpurple':          '#9370DB',
    'mediumseagreen':        '#3CB371',
    'mediumslateblue':       '#7B68EE',
    'mediumspringgreen':     '#00FA9A',
    'mediumturquoise':       '#48D1CC',
    'mediumvioletred':       '#C71585',
    'midnightblue':          '#191970',
    'mintcream':             '#F5FFFA',
    'mistyrose':             '#FFE4E1',
    'moccasin':              '#FFE4B5',
    'navajowhite':           '#FFDEAD',
    'navy':                  '#000080',
    'oldlace':               '#FDF5E6',
    'olive':                 '#808000',
    'olivedrab':             '#6B8E23',
    'orange':                '#FFA500',
    'orangered':             '#FF4500',
    'orchid':                '#DA70D6',
    'palegoldenrod':         '#EEE8AA',
    'palegreen':             '#98FB98',
    'paleturquoise':         '#AFEEEE',
    'palevioletred':         '#DB7093',
    'papayawhip':            '#FFEFD5',
    'peachpuff':             '#FFDAB9',
    'peru':                  '#CD853F',
    'pink':                  '#FFC0CB',
    'plum':                  '#DDA0DD',
    'powderblue':            '#B0E0E6',
    'purple':                '#800080',
    'red':                   '#FF0000',
    'rosybrown':             '#BC8F8F',
    'royalblue':             '#4169E1',
    'saddlebrown':           '#8B4513',
    'salmon':                '#FA8072',
    'sandybrown':            '#F4A460',
    'seagreen':              '#2E8B57',
    'seashell':              '#FFF5EE',
    'sienna':                '#A0522D',
    'silver':                '#C0C0C0',
    'skyblue':               '#87CEEB',
    'slateblue':             '#6A5ACD',
    'slategray':             '#708090',
    'slategrey':             '#708090',
    'snow':                  '#FFFAFA',
    'springgreen':           '#00FF7F',
    'steelblue':             '#4682B4',
    'tan':                   '#D2B48C',
    'teal':                  '#008080',
    'thistle':               '#D8BFD8',
    'tomato':                '#FF6347',
    'turquoise':             '#40E0D0',
    'violet':                '#EE82EE',
    'wheat':                 '#F5DEB3',
    'white':                 '#FFFFFF',
    'whitesmoke':            '#F5F5F5',
    'yellow':                '#FFFF00',
    'yellowgreen':           '#9ACD32',
}

css = CSS_HEX

# CSS name -> (English display name, French display name)
CSS_FR = {
 'aliceblue':        ("Alice Blue", "Bleu Alice"),
 'antiquewhite':     ("Antique White", "Blanc antique"),
 'aquamarine':       ("Aquamarine", "Aigue-marine"),
 'azure':            ("Azure", "Azur"),
 'beige':            ("Beige", "Beige"),
 'bisque':           ("Bisque", "Bisque"),
 'black':            ("Black", "Noir"),
 'blanchedalmond':   ("Blanched Almond", "Amande blanchie"),
 'blue':             ("Blue", "Bleu"),
 'blueviolet':       ("Blue Violet", "Violet bleuté"),
 'brown':            ("Brown", "Brun"),
 'burlywood':        ("Burlywood", "Bois clair"),
 'cadetblue':        ("Cadet Blue", "Bleu cadet"),
 'chartreuse':       ("Chartreuse", "Chartreuse"),
 'chocolate':        ("Chocolate", "Chocolat"),
 'coral':            ("Coral", "Corail"),
 'cornflowerblue':   ("Cornflower Blue", "Bleu bleuet"),
 'cornsilk':         ("Cornsilk", "Soie de maïs"),
 'crimson':          ("Crimson", "Cramoisi"),
 'cyan':             ("Cyan", "Cyan"),
 'darkblue':         ("Dark Blue", "Bleu foncé"),
 'darkcyan':         ("Dark Cyan", "Cyan foncé"),
 'darkgoldenrod':    ("Dark Goldenrod", "Vieil or foncé"),
 'darkgray':         ("Dark Gray", "Gris foncé"),
 'darkgreen':        ("Dark Green", "Vert foncé"),
 'darkkhaki':        ("Dark Khaki", "Kaki foncé"),
 'darkmagenta':      ("Dark Magenta", "Magenta foncé"),
 'darkolivegreen':   ("Dark Olive Green", "Vert olive foncé"),
 'darkorange':       ("Dark Orange", "Orange foncé"),
 'darkorchid':       ("Dark Orchid", "Orchidée foncé"),
 'darkred':          ("Dark Red", "Rouge foncé"),
 'darksalmon':       ("Dark Salmon", "Saumon foncé"),
 'darkseagreen':     ("Dark Sea Green", "Vert d'eau foncé"),
 'darkslateblue':    ("Dark Slate Blue", "Bleu ardoise foncé"),
 'darkslategray':    ("Dark Slate Gray", "Gris ardoise foncé"),
 'darkturquoise':    ("Dark Turquoise", "Turquoise foncé"),
 'darkviolet':       ("Dark Violet", "Violet foncé"),
 'deeppink':         ("Deep Pink", "Rose intense"),
 'deepskyblue':      ("Deep Sky Blue", "Bleu ciel intense"),
 'dimgray':          ("Dim Gray", "Gris terne"),
 'dodgerblue':       ("Dodger Blue", "Bleu Dodger"),
 'firebrick':        ("Firebrick", "Brique"),
 'floralwhite':      ("Floral White", "Blanc floral"),
 'forestgreen':      ("Forest Green", "Vert forêt"),
 'gainsboro':        ("Gainsboro", "Gainsboro"),
 'ghostwhite':       ("Ghost White", "Blanc fantôme"),
 'gold':             ("Gold", "Or"),
 'goldenrod':        ("Goldenrod", "Vieil or"),
 'gray':             ("Gray", "Gris"),
 'green':            ("Green", "Vert"),
 'greenyellow':      ("Green Yellow", "Jaune-vert"),
 'honeydew':         ("Honeydew", "Miellat"),
 'hotpink':          ("Hot Pink", "Rose vif"),
 'indianred':        ("Indian Red", "Rouge indien"),
 'indigo':           ("Indigo", "Indigo"),
 'ivory':            ("Ivory", "Ivoire"),
 'khaki':            ("Khaki", "Kaki"),
 'lavender':         ("Lavender", "Lavande"),
 'lavenderblush':    ("Lavender Blush", "Lavande rosée"),
 'lawngreen':        ("Lawn Green", "Vert gazon"),
 'lemonchiffon':     ("Lemon Chiffon", "Mousseline citron"),
 'lightblue':        ("Light Blue", "Bleu clair"),
 'lightcoral':       ("Light Coral", "Corail clair"),
 'lightcyan':        ("Light Cyan", "Cyan clair"),
 'lightgoldenrodyellow': ("Light Goldenrod Yellow", "Jaune vieil or clair"),
 'lightgray':        ("Light Gray", "Gris clair"),
 'lightgreen':       ("Light Green", "Vert clair"),
 'lightpink':        ("Light Pink", "Rose clair"),
 'lightsalmon':      ("Light Salmon", "Saumon clair"),
 'lightseagreen':    ("Light Sea Green", "Vert d'eau clair"),
 'lightskyblue':     ("Light Sky Blue", "Bleu ciel clair"),
 'lightslategray':   ("Light Slate Gray", "Gris ardoise clair"),
 'lightsteelblue':   ("Light Steel Blue", "Bleu acier clair"),
 'lightyellow':      ("Light Yellow", "Jaune clair"),
 'lime':             ("Lime", "Vert lime"),
 'limegreen':        ("Lime Green", "Vert lime foncé"),
 'linen':            ("Linen", "Lin"),
 'magenta':          ("Magenta", "Magenta"),
 'maroon':           ("Maroon", "Grenat"),
 'mediumaquamarine': ("Medium Aquamarine", "Aigue-marine moyen"),
 'mediumblue':       ("Medium Blue", "Bleu moyen"),
 'mediumorchid':     ("Medium Orchid", "Orchidée moyen"),
 'mediumpurple':     ("Medium Purple", "Pourpre moyen"),
 'mediumseagreen':   ("Medium Sea Green", "Vert d'eau moyen"),
 'mediumslateblue':  ("Medium Slate Blue", "Bleu ardoise moyen"),
 'mediumspringgreen':("Medium Spring Green", "Vert printemps moyen"),
 'mediumturquoise':  ("Medium Turquoise", "Turquoise moyen"),
 'mediumvioletred':  ("Medium Violet Red", "Rouge violacé moyen"),
 'midnightblue':     ("Midnight Blue", "Bleu de minuit"),
 'mintcream':        ("Mint Cream", "Crème de menthe"),
 'mistyrose':        ("Misty Rose", "Rose brumeux"),
 'moccasin':         ("Moccasin", "Mocassin"),
 'navajowhite':      ("Navajo White", "Blanc navajo"),
 'navy':             ("Navy", "Bleu marine"),
 'oldlace':          ("Old Lace", "Vieille dentelle"),
 'olive':            ("Olive", "Olive"),
 'olivedrab':        ("Olive Drab", "Olive terne"),
 'orange':           ("Orange", "Orange"),
 'orangered':        ("Orange Red", "Rouge orangé"),
 'orchid':           ("Orchid", "Orchidée"),
 'palegoldenrod':    ("Pale Goldenrod", "Vieil or pâle"),
 'palegreen':        ("Pale Green", "Vert pâle"),
 'paleturquoise':    ("Pale Turquoise", "Turquoise pâle"),
 'palevioletred':    ("Pale Violet Red", "Rouge violacé pâle"),
 'papayawhip':       ("Papaya Whip", "Papaye"),
 'peachpuff':        ("Peach Puff", "Pêche douce"),
 'peru':             ("Peru", "Pérou"),
 'pink':             ("Pink", "Rose"),
 'plum':             ("Plum", "Prune"),
 'powderblue':       ("Powder Blue", "Bleu poudre"),
 'purple':           ("Purple", "Pourpre"),
 'red':              ("Red", "Rouge"),
 'rosybrown':        ("Rosy Brown", "Brun rosé"),
 'royalblue':        ("Royal Blue", "Bleu roi"),
 'saddlebrown':      ("Saddle Brown", "Brun cuir"),
 'salmon':           ("Salmon", "Saumon"),
 'sandybrown':       ("Sandy Brown", "Brun sable"),
 'seagreen':         ("Sea Green", "Vert d'eau"),
 'seashell':         ("Seashell", "Coquillage"),
 'sienna':           ("Sienna", "Terre de Sienne"),
 'silver':           ("Silver", "Argent"),
 'skyblue':          ("Sky Blue", "Bleu ciel"),
 'slateblue':        ("Slate Blue", "Bleu ardoise"),
 'slategray':        ("Slate Gray", "Gris ardoise"),
 'snow':             ("Snow", "Neige"),
 'springgreen':      ("Spring Green", "Vert printemps"),
 'steelblue':        ("Steel Blue", "Bleu acier"),
 'tan':              ("Tan", "Beige fauve"),
 'teal':             ("Teal", "Sarcelle"),
 'thistle':          ("Thistle", "Chardon"),
 'tomato':           ("Tomato", "Tomate"),
 'turquoise':        ("Turquoise", "Turquoise"),
 'violet':           ("Violet", "Violet clair"),
 'wheat':            ("Wheat", "Blé"),
 'white':            ("White", "Blanc"),
 'whitesmoke':       ("White Smoke", "Blanc fumée"),
 'yellow':           ("Yellow", "Jaune"),
 'yellowgreen':      ("Yellow Green", "Vert jaune"),
}

# Aliases we deliberately skip (duplicate hexes of an entry we keep).
SKIP = {'aqua', 'fuchsia', 'darkgrey', 'dimgrey', 'grey', 'lightgrey',
        'lightslategrey', 'slategrey', 'darkslategrey'}

entries = []  # (hex, en, fr, source)
for name in sorted(css):
    if name in SKIP:
        continue
    if name not in CSS_FR:
        raise SystemExit("missing French name for CSS colour: " + name)
    en, fr = CSS_FR[name]
    entries.append((css[name].upper(), en, fr, 'css'))

# Traditional pigment / everyday colours, with the French name that people
# actually use. Hex values are the conventional ones for each pigment.
TRAD = [
 ("#003153", "Prussian Blue",      "Bleu de Prusse"),
 ("#002FA7", "Klein Blue",         "Bleu Klein"),
 ("#120A8F", "Ultramarine",        "Outremer"),
 ("#0F52BA", "Sapphire",           "Saphir"),
 ("#26619C", "Lapis Lazuli",       "Lapis-lazuli"),
 ("#318CE7", "Bleu de France",     "Bleu de France"),
 ("#007BA7", "Cerulean",           "Bleu céruléen"),
 ("#048B9A", "Teal Blue",          "Bleu canard"),
 ("#00666B", "Petrol Blue",        "Bleu pétrole"),
 ("#0F056B", "Night Blue",         "Bleu nuit"),
 ("#CCCCFF", "Periwinkle",         "Pervenche"),
 ("#ACE1AF", "Celadon",            "Céladon"),
 ("#95A595", "Verdigris",          "Vert-de-gris"),
 ("#50C878", "Emerald",            "Émeraude"),
 ("#00A86B", "Jade",               "Jade"),
 ("#16B84E", "Mint Green",         "Vert menthe"),
 ("#8DB600", "Apple Green",        "Vert pomme"),
 ("#BEF574", "Pistachio",          "Pistache"),
 ("#095228", "Fir Green",          "Vert sapin"),
 ("#01796F", "Pine Green",         "Vert pin"),
 ("#40826D", "Viridian",           "Vert véronèse"),
 ("#4B5320", "Army Green",         "Vert armée"),
 ("#78866B", "Camouflage Green",   "Vert camouflage"),
 ("#E4D96F", "Straw",              "Jaune paille"),
 ("#F4C430", "Saffron",            "Safran"),
 ("#FFDB58", "Mustard",            "Moutarde"),
 ("#FFBF00", "Amber",              "Ambre"),
 ("#D4AF37", "Metallic Gold",      "Or métallique"),
 ("#CC7722", "Ochre",              "Ocre"),
 ("#C2B280", "Sand",               "Sable"),
 ("#F3E5AB", "Vanilla",            "Vanille"),
 ("#F7E7CE", "Champagne",          "Champagne"),
 ("#FFFDD0", "Cream",              "Crème"),
 ("#F0EAD6", "Eggshell",           "Coquille d'œuf"),
 ("#E5E4E2", "Platinum",           "Platine"),
 ("#CEC8C8", "Pearl Gray",         "Gris perle"),
 ("#71797E", "Steel Gray",         "Gris acier"),
 ("#36454F", "Charcoal",           "Anthracite"),
 ("#353839", "Onyx",               "Onyx"),
 ("#343434", "Jet",                "Noir de jais"),
 ("#483C32", "Taupe",              "Taupe"),
 ("#3D2B1F", "Bistre",             "Bistre"),
 ("#6F4E37", "Coffee",             "Café"),
 ("#4B3621", "Dark Coffee",        "Café noir"),
 ("#B87333", "Copper",             "Cuivre"),
 ("#CD7F32", "Bronze",             "Bronze"),
 ("#B7410E", "Rust",               "Rouille"),
 ("#E97451", "Burnt Sienna",       "Terre de Sienne brûlée"),
 ("#CC5500", "Burnt Orange",       "Orange brûlé"),
 ("#FF7518", "Pumpkin",            "Citrouille"),
 ("#ED9121", "Carrot Orange",      "Orange carotte"),
 ("#E67E30", "Apricot",            "Abricot"),
 ("#FFE5B4", "Peach",              "Pêche"),
 ("#E34234", "Vermilion",          "Vermillon"),
 ("#C60800", "Poppy Red",          "Coquelicot"),
 ("#EE3B3B", "Madder",             "Garance"),
 ("#E32636", "Alizarin Crimson",   "Rouge alizarine"),
 ("#E60026", "Carmine",            "Carmin"),
 ("#C41E3A", "Cardinal",           "Rouge cardinal"),
 ("#6D071A", "Bordeaux",           "Bordeaux"),
 ("#AC1E44", "Wine Lees",          "Lie de vin"),
 ("#7C0A02", "Oxblood",            "Sang de bœuf"),
 ("#DE3163", "Cerise",             "Cerise"),
 ("#E30B5D", "Raspberry",          "Framboise"),
 ("#F4C2C2", "Baby Pink",          "Rose dragée"),
 ("#9F2B68", "Amaranth",           "Amarante"),
 ("#370028", "Aubergine",          "Aubergine"),
 ("#E0B0FF", "Mauve",              "Mauve"),
 ("#CFA0E9", "Parma Violet",       "Parme"),
 ("#B666D2", "Lilac",              "Lilas"),
 ("#C9A0DC", "Wisteria",           "Glycine"),
 ("#7F00FF", "Violet",             "Violet"),
]
for hx, en, fr in TRAD:
    entries.append((hx.upper(), en, fr, 'trad'))

# Guard against two entries claiming the same hex.
seen = {}
for hx, en, fr, src in entries:
    if hx in seen:
        raise SystemExit("duplicate hex %s: %s vs %s" % (hx, seen[hx], en))
    seen[hx] = en

out = io.StringIO()
out.write("""// ChromaCam — named colour catalogue.
// Generated by src_material/chromacam/gen_colors.py. Each entry is [hex, English name, French name].
// Sources: the 138 unique CSS/X11 named colours (authoritative hex values) plus a
// curated set of traditional pigment and everyday colours whose French names are
// in common use. Do not hand-edit — regenerate instead.
window.CHROMACAM_COLORS = [
""")
for hx, en, fr, src in entries:
    out.write('  ["%s", %s, %s],\n' % (hx, json.dumps(en, ensure_ascii=False), json.dumps(fr, ensure_ascii=False)))
out.write("];\n")

dest = sys.argv[1]
open(dest, 'w', encoding='utf-8').write(out.getvalue())
print("wrote %d colours to %s" % (len(entries), dest))
